// <auto-generated />
using System;
using ApisPedido.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApisPedido.Data.Migrations
{
    [DbContext(typeof(AdoptaDbContext))]
    partial class AdoptaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApisPedido.Models.Fundacion", b =>
                {
                    b.Property<int>("IdFundacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Fundacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFundacion"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("Id_Usuario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdFundacion");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("FUNDACION", (string)null);
                });

            modelBuilder.Entity("ApisPedido.Models.Mascota", b =>
                {
                    b.Property<int>("IdMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Mascota");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMascota"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IdFundacion")
                        .HasColumnType("int")
                        .HasColumnName("Id_Fundacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Tamano")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdMascota");

                    b.HasIndex("IdFundacion");

                    b.ToTable("MASCOTA", null, t =>
                        {
                            t.HasCheckConstraint("CK_MASCOTA_Edad", "[Edad] >= 0 AND [Edad] <= 50");

                            t.HasCheckConstraint("CK_MASCOTA_Estado", "[Estado] IN ('Disponible','EnProceso','Adoptada','Retirada')");

                            t.HasCheckConstraint("CK_MASCOTA_Tamano", "[Tamano] IN ('Pequeno','Mediano','Grande')");
                        });
                });

            modelBuilder.Entity("ApisPedido.Models.SolicitudAdopcion", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Solicitud");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IdMascota")
                        .HasColumnType("int")
                        .HasColumnName("Id_Mascota");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("Id_Usuario");

                    b.Property<string>("Mensaje")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("IdMascota");

                    b.HasIndex("IdUsuario");

                    b.ToTable("SOLICITUD_ADOPCION", null, t =>
                        {
                            t.HasCheckConstraint("CK_SOLICITUD_Estado", "[Estado] IN ('Pendiente','EnRevision','Aprobada','Rechazada','Completada')");
                        });
                });

            modelBuilder.Entity("ApisPedido.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("ApisPedido.Models.Fundacion", b =>
                {
                    b.HasOne("ApisPedido.Models.Usuario", "Usuario")
                        .WithOne("Fundacion")
                        .HasForeignKey("ApisPedido.Models.Fundacion", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApisPedido.Models.Mascota", b =>
                {
                    b.HasOne("ApisPedido.Models.Fundacion", "Fundacion")
                        .WithMany("Mascotas")
                        .HasForeignKey("IdFundacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fundacion");
                });

            modelBuilder.Entity("ApisPedido.Models.SolicitudAdopcion", b =>
                {
                    b.HasOne("ApisPedido.Models.Mascota", "Mascota")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdMascota")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApisPedido.Models.Usuario", "Usuario")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mascota");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApisPedido.Models.Fundacion", b =>
                {
                    b.Navigation("Mascotas");
                });

            modelBuilder.Entity("ApisPedido.Models.Mascota", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("ApisPedido.Models.Usuario", b =>
                {
                    b.Navigation("Fundacion");

                    b.Navigation("Solicitudes");
                });
#pragma warning restore 612, 618
        }
    }
}
